addons = [
    "str",
    "str",
    "str",
    "str",
    "str",
    "str",
    "str",
    "str"
]
upstream_url = "str"
invite_url = "str"
privacy_info = "str"

[bot]
token = "str"
cse_keys = [
    "str",
    "str",
    "str"
]
cse_engine = "str"
prefix = "str"
activity_name = "str"
activity_type = "str"
status = "str"
ignored_exceptions = [
    "str",
    "str",
    "str",
    "str"
]

[database]
user = "str"
password = "str"
database = "str"
host = "str"
